name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.yourdomain.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build . --file Dockerfile --tag registry.mgfhub.com/mgfhub:latest

      - name: Push Docker image
        run: |
          docker push registry.mgfhub.com/mgfhub:latest