name: Github Actions Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
<<<<<<< HEAD
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.18
=======
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
>>>>>>> 8cb45c31119486208ee2473a7cad0e2af64d4918
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    